// Blog content. Static, SEO-friendly articles tied to the app's approach.
// Body blocks: {p}, {h}, {ul:[...]}, {tip}.

export const POSTS = [
  {
    slug: "how-many-calories-to-lose-fat",
    title: "How Many Calories Should You Eat to Lose Fat?",
    excerpt: "Forget generic calculators. Here's how to find the number that actually works for your body — and why it should change over time.",
    tag: "Nutrition", date: "2026-06-01", readMins: 5,
    body: [
      { p: "Every fat-loss plan starts with one number: how many calories you eat per day. Get it roughly right and the fat comes off. Get it wrong and you either stall or burn out. The good news is you don't need to guess." },
      { h: "Start with maintenance" },
      { p: "Maintenance is the calories that keep your weight stable. A formula (the Mifflin-St Jeor equation) estimates it from your sex, age, height, weight and activity. That's where PRIME starts you — but a formula is only an estimate. Two people with identical stats can differ by 300+ calories." },
      { h: "Then create a modest deficit" },
      { p: "To lose fat, eat below maintenance. A deficit of 15-20% (roughly 300-600 kcal) loses fat steadily while protecting muscle and energy. Crash diets of 1,000+ kcal deficits backfire: you lose muscle, your training tanks, and you rebound." },
      { ul: ["Aim to lose about 0.5-1% of body weight per week", "Keep protein high to hold onto muscle", "Don't drop below ~1,500 kcal (men) / ~1,200 kcal (women) without supervision"] },
      { h: "The part most apps miss" },
      { p: "Your real maintenance changes as you lose weight and as your body adapts. The smartest approach is to measure it from your own data: compare your actual average intake against your weight-trend over 2-3 weeks, and adjust. That's exactly what PRIME's adaptive engine does once you've logged enough days — so your target stays honest instead of frozen at a day-one guess." },
      { tip: "Weigh yourself a few mornings a week and log everything you eat for two weeks. Trends beat single days every time." },
    ],
  },
  {
    slug: "protein-for-indian-vegetarians",
    title: "Protein for Indian Vegetarians: Hitting Your Target Without Meat",
    excerpt: "Yes, you can hit 120g+ of protein a day on a vegetarian Indian diet. Here's the playbook.",
    tag: "Indian Diet", date: "2026-05-24", readMins: 6,
    body: [
      { p: "The biggest myth in Indian fitness is that you need chicken and eggs to build muscle. You don't — but vegetarian protein does take a little planning, because most Indian veg staples are carb-heavy." },
      { h: "Your high-protein veg MVPs" },
      { ul: ["Paneer — ~18g protein per 100g", "Curd / Greek yogurt — 11-18g per bowl", "Dals and legumes (rajma, chana, moong) — 15-18g per cooked cup", "Soya chunks — a massive ~26g per 50g dry", "Whey or a plant protein scoop — 24g in seconds", "Tofu, sprouts, and roasted chana for snacks"] },
      { h: "Build each meal around protein first" },
      { p: "Instead of rice-and-a-little-dal, flip it: a big bowl of dal or 100g paneer first, then the carbs around it. A simple day — paneer paratha + curd at breakfast, rajma-chawal at lunch, a soya stir-fry snack, and dal + sabzi + curd at dinner — clears 100g without trying." },
      { h: "How much do you need?" },
      { p: "Aim for roughly 1.6-2.2g of protein per kg of body weight. A 70kg person targeting body recomposition wants around 130-150g a day. Spread it across 3-4 meals so each has 25-40g." },
      { p: "PRIME's recipes are tagged veg/non-veg and show protein per serving, and the diet planner builds your day to hit your protein target automatically. Log a few meals and you'll see exactly where your gaps are." },
    ],
  },
  {
    slug: "beginner-first-two-weeks",
    title: "Your First 2 Weeks in the Gym: Why Starting Slow Wins",
    excerpt: "New lifters who go all-out in week one usually quit by week three. The fix is an anatomical adaptation phase.",
    tag: "Getting Started", date: "2026-05-18", readMins: 5,
    body: [
      { p: "When you're motivated, it's tempting to train to failure on day one. Don't. The people who transform aren't the ones who go hardest in week one — they're the ones still training in month six." },
      { h: "Your tendons lag behind your muscles" },
      { p: "In the first few weeks, most of your strength gains are neural — your brain learning to recruit muscle. Your muscles adapt fast, but tendons, ligaments and joints take longer. Hammer them too soon and you get tendinitis or a tweaked back, not gains." },
      { h: "What a foundation phase looks like" },
      { ul: ["Full-body sessions, 3 days a week", "Lighter loads at an effort of about 5-6 out of 10", "Higher reps (12-15) to groove technique", "Full range of motion on every rep", "Mobility work and easy cardio between sessions"] },
      { h: "Then progress" },
      { p: "After 1-2 weeks of building the base, you add load and structure. PRIME does this automatically: tell it you're new (or returning after a break) and it inserts a Foundation phase before the main 28-week program, then ramps you up safely." },
      { tip: "Soreness is normal; sharp joint pain is not. If a movement hurts a joint, drop the weight or swap the exercise." },
    ],
  },
  {
    slug: "north-vs-south-indian-diet-fat-loss",
    title: "North vs South Indian Diet for Fat Loss: Which Is Better?",
    excerpt: "Both can work brilliantly — or wreck your deficit. It comes down to a few high-impact choices.",
    tag: "Indian Diet", date: "2026-05-10", readMins: 5,
    body: [
      { p: "There's no single best regional diet. North and South Indian food can each be lean and protein-rich, or oily and carb-heavy. The winners and losers are in the details." },
      { h: "Where calories sneak in" },
      { ul: ["Cooking oil and ghee — measure it; a couple of tablespoons is 200-300 kcal", "Deep-fried items — pakora, vada, samosa, poori", "Refined carbs in big portions — white rice mountains, naan, bhature", "Sugary chai and sweets"] },
      { h: "North Indian, done lean" },
      { p: "Grill or air-fry your tandoori chicken and paneer tikka, swap naan for 1-2 phulka or millet rotis, load up on dal and sabzi, and keep curries low-oil. Rajma and chole are protein-rich when you go easy on the tempering." },
      { h: "South Indian, done lean" },
      { p: "Idli, dosa and sambar are fine — the trap is the oil and coconut chutney quantity. Add eggs or extra dal for protein, favour steamed (idli) over fried, and keep curd-rice portions sensible." },
      { p: "Pick the cuisine you'll actually enjoy and stick to. In PRIME you set North or South and veg/non-veg, and the meal plans and recipes adapt — calories and protein shown for each." },
    ],
  },
  {
    slug: "progressive-overload-explained",
    title: "Progressive Overload: The Only Rule That Builds Muscle",
    excerpt: "If your workouts look the same every week, your body has no reason to change. Here's how to keep moving forward.",
    tag: "Training", date: "2026-05-03", readMins: 4,
    body: [
      { p: "Muscle grows in response to a stimulus it isn't used to. Lift the same weight for the same reps forever and you maintain — you don't build. Progressive overload is the principle of gradually asking for more." },
      { h: "Ways to add overload" },
      { ul: ["Add weight (the classic)", "Add a rep or two at the same weight", "Add a set", "Improve form / range of motion", "Reduce rest between sets", "Slow the lowering (eccentric) phase"] },
      { h: "A simple rule that works" },
      { p: "Pick a rep range, say 8-12. When you can hit the top of the range (12) with good form on all sets, add a little weight next time and start again at the bottom. This is called double progression, and it's almost foolproof for beginners and intermediates." },
      { h: "Track it or lose it" },
      { p: "You can't beat last week if you don't remember last week. PRIME logs your weight and reps per set and shows your previous best on each exercise, so every session you know exactly what to chase." },
    ],
  },
  {
    slug: "why-the-scale-lies",
    title: "Why the Scale Lies — and What to Track Instead",
    excerpt: "Your weight can swing 2kg in a day with zero fat change. Stop letting one number ruin your morning.",
    tag: "Mindset", date: "2026-04-26", readMins: 4,
    body: [
      { p: "You ate perfectly, trained hard, and the scale went up 1.5kg overnight. Did you gain fat? Almost certainly not. The scale measures everything — water, food in transit, glycogen, hormones — not just fat." },
      { h: "What moves the scale day to day" },
      { ul: ["Salt and carb intake (water retention)", "A hard workout (muscle holds water as it repairs)", "Time of day and hydration", "For women, the menstrual cycle", "Simply needing the bathroom"] },
      { h: "Track the trend, not the day" },
      { p: "Weigh yourself a few mornings a week and watch the weekly average. A line that drifts down over 2-3 weeks means you're losing fat, even if individual days bounce around." },
      { h: "Use more than one mirror" },
      { p: "Progress photos every 2 weeks, how your clothes fit, your strength in the gym, and your waist measurement all tell the real story. PRIME plots your weight trend, stores private progress photos, and can even analyse them — so you judge yourself on the trend, not a bad-water morning." },
    ],
  },
  {
    slug: "home-workout-with-dumbbells",
    title: "Build a Complete Home Workout With Just Dumbbells",
    excerpt: "No gym, no problem. A pair of adjustable dumbbells covers every muscle group.",
    tag: "Training", date: "2026-04-19", readMins: 5,
    body: [
      { p: "You don't need a fully-equipped gym to build muscle. A single pair of dumbbells (ideally adjustable) plus a bench or sturdy chair lets you train your whole body effectively for years." },
      { h: "A simple full-body template" },
      { ul: ["Legs: goblet squat, dumbbell Romanian deadlift, reverse lunge", "Push: dumbbell floor press, shoulder press, lateral raise", "Pull: bent-over row, one-arm row, hammer curl", "Core: plank, lying leg raise, weighted crunch"] },
      { h: "Make light weights hard" },
      { p: "Limited weight? Increase the challenge with tempo (3 seconds down), pauses at the hardest point, higher reps, and shorter rest. A 12kg dumbbell taken to a controlled 20 reps is no joke." },
      { h: "Progress without buying plates" },
      { p: "Add reps, add sets, slow the eccentric, or move to single-limb versions (one-arm, one-leg) to double the load on the working side. PRIME's home and bodyweight modes automatically swap in dumbbell and calisthenic variants for every exercise in your plan." },
    ],
  },
  {
    slug: "bodyweight-pull-ups-push-ups",
    title: "Bodyweight Training: Master Push-Ups and Pull-Ups",
    excerpt: "The two best upper-body exercises need zero equipment. Here's how to progress from zero to strong.",
    tag: "Training", date: "2026-04-12", readMins: 5,
    body: [
      { p: "If you only trained push-ups and pull-ups, you'd build an impressive upper body. They're free, scalable, and brutally effective — you just need a progression path." },
      { h: "Push-up progression" },
      { ul: ["Can't do one? Start with incline push-ups (hands on a table), then knees", "Then full push-ups, adding reps each week", "Then decline (feet elevated) and tempo push-ups", "Advanced: archer and one-arm progressions"] },
      { h: "Pull-up progression" },
      { ul: ["Start with inverted rows under a sturdy table", "Then dead-hangs and negatives (jump up, lower slowly for 5s)", "Then band-assisted pull-ups", "Then full pull-ups — chase one extra rep at a time"] },
      { h: "Don't neglect the rest" },
      { p: "Pair these with squats, lunges, hip hinges and planks for a complete bodyweight routine. PRIME's Bodyweight mode builds your whole 28-week plan around moves like these, with form videos for each." },
    ],
  },
  {
    slug: "toning-vs-building-muscle",
    title: "The Truth About Toning vs Building Muscle",
    excerpt: "Spoiler: there's no such thing as toning. What you actually want is muscle plus lower body fat.",
    tag: "Mindset", date: "2026-04-05", readMins: 4,
    body: [
      { p: "Toned is the look of having a reasonable amount of muscle with low enough body fat to see it. You can't tone a muscle — you can only build it or lose it, and reveal it by losing fat." },
      { h: "Light weights and high reps won't do it" },
      { p: "The classic toning advice — tiny weights for endless reps — doesn't build the muscle that creates the toned look. You need meaningful resistance and progressive overload, the same as anyone chasing size, just paired with a controlled diet." },
      { h: "The real recipe" },
      { ul: ["Lift with challenging weights (progressive overload)", "Eat enough protein to build and keep muscle", "Run a modest calorie deficit to reveal it", "Be patient — visible change takes months, not weeks"] },
      { p: "Whether your goal says lose fat, recomp, or build muscle, the training looks similar — only the calories differ. PRIME sets both for you based on your goal." },
    ],
  },
  {
    slug: "how-much-protein-do-you-need",
    title: "How Much Protein Do You Really Need?",
    excerpt: "Not as much as the supplement ads claim — but more than most people eat. Here's the science-backed number.",
    tag: "Nutrition", date: "2026-03-29", readMins: 4,
    body: [
      { p: "Protein is the one macronutrient almost everyone under-eats and over-complicates. You don't need a gram-by-gram obsession, but you do need a target." },
      { h: "The number that matters" },
      { p: "Research converges on roughly 1.6 to 2.2 grams of protein per kilogram of body weight per day for people training to build or keep muscle. Around 1.6 is plenty for most; the higher end helps when you're in a calorie deficit." },
      { h: "A practical shortcut" },
      { p: "Heavier or higher body fat? Base it on your target weight rather than current weight, so you don't chase an unnecessarily huge number. A 90kg person aiming for 75kg can target protein around 75-90 x 1.8, not 90 x 2.2." },
      { h: "Why it matters so much in a deficit" },
      { p: "When you eat less, your body can break down muscle for fuel. High protein plus resistance training tells it to burn fat and keep the muscle. PRIME calculates your protein target on a lean-mass basis and tracks it live as you log." },
    ],
  },
  {
    slug: "deload-weeks-explained",
    title: "Deload Weeks: Why Doing Less Makes You Stronger",
    excerpt: "Pushing hard every week eventually backfires. A planned easy week is how you keep progressing.",
    tag: "Recovery", date: "2026-03-22", readMins: 4,
    body: [
      { p: "More is not always better. Train hard for many weeks straight and fatigue accumulates faster than your body can recover — progress stalls, joints ache, motivation dips. A deload is the planned solution." },
      { h: "What a deload is" },
      { p: "A deload is a lighter week — typically every 4-8 weeks — where you cut volume and/or intensity by about 10-40%. Fewer sets, lighter loads, or both. You're not detraining; you're letting accumulated fatigue clear so your fitness can surface." },
      { h: "Signs you need one" },
      { ul: ["Lifts that felt easy now feel heavy", "Nagging aches and poor sleep", "Dreading the gym", "Strength flat or going backwards for 2+ weeks"] },
      { p: "PRIME schedules deload weeks into your program automatically (lighter loads and a set fewer), so recovery is built in rather than something you only take when you're already run down." },
    ],
  },
  {
    slug: "meal-prep-indian-households",
    title: "Meal Prep for Indian Households (Veg & Non-Veg)",
    excerpt: "You don't need bland chicken-and-broccoli boxes. Here's meal prep that fits real Indian kitchens.",
    tag: "Indian Diet", date: "2026-03-15", readMins: 5,
    body: [
      { p: "Meal prep doesn't mean seven identical containers. For most Indian homes, it means prepping components so hitting your protein and calories is effortless on busy days." },
      { h: "Prep components, not full meals" },
      { ul: ["Boil and portion dal, rajma or chole for the week", "Marinate chicken/paneer in batches; grill as needed", "Pre-chop onion-tomato masala base", "Boil eggs, soak sprouts, portion curd", "Cook a grain (rice/millet) once, reheat through the week"] },
      { h: "Make protein the default" },
      { p: "The hardest macro to hit is protein, so prep it first. If there's always cooked dal, boiled eggs, or marinated paneer/chicken ready, you'll never end a day 40g short." },
      { h: "Keep it flexible" },
      { p: "Cook for the whole family and adjust your portions — more protein and veg, measured oil, controlled rice. PRIME's recipes give you ingredients and per-serving macros so you can scale any dish to your day." },
    ],
  },
  {
    slug: "body-recomposition",
    title: "Recomposition: Can You Lose Fat and Gain Muscle at Once?",
    excerpt: "For some people, yes — and it might be exactly the goal you want.",
    tag: "Training", date: "2026-03-08", readMins: 5,
    body: [
      { p: "Conventional wisdom says you must bulk to gain muscle and cut to lose fat. But many people can do both at once — body recomposition — under the right conditions." },
      { h: "Who recomps best" },
      { ul: ["Beginners in their first year of training", "People returning after a long break (muscle memory)", "Those carrying higher body fat with plenty to lose", "Anyone newly dialling in protein and progressive training"] },
      { h: "How to set it up" },
      { p: "Eat at or just slightly below maintenance, push protein high (around 2g/kg), and train with progressive overload. Fat comes off slowly while muscle builds — the scale may barely move while your mirror and measurements change a lot." },
      { h: "Be patient with the scale" },
      { p: "Because you're gaining muscle as you lose fat, weight loss looks slow. Judge recomp by photos, measurements and strength, not the scale alone. PRIME's prime (recomp) goal sets a near-maintenance calorie target and high protein for exactly this." },
    ],
  },
  {
    slug: "steps-neat-fat-loss",
    title: "Steps and NEAT: The Most Underrated Fat-Loss Tool",
    excerpt: "The calories you burn outside the gym dwarf the ones you burn in it. Here's how to use them.",
    tag: "Nutrition", date: "2026-03-01", readMins: 4,
    body: [
      { p: "A tough workout might burn 300-400 calories. The rest of your day — walking, fidgeting, chores, standing — can burn far more. That's NEAT: non-exercise activity thermogenesis, and it's the lever most people ignore." },
      { h: "Why NEAT matters" },
      { p: "When you diet, your body quietly reduces NEAT — you move less without noticing. Consciously keeping steps up offsets that, keeping your deficit intact without slashing food further." },
      { h: "A simple target" },
      { ul: ["Sedentary now? Start around 7,000-8,000 steps", "Fat-loss sweet spot: 9,000-11,000 steps", "Take walking calls, park further away, walk after meals", "Track it — what gets measured gets done"] },
      { p: "PRIME sets a step goal based on your objective (higher for fat loss) and tracks it alongside your calories, so movement is part of the plan, not an afterthought." },
    ],
  },
  {
    slug: "sleep-and-muscle",
    title: "Sleep and Muscle: The Recovery You're Ignoring",
    excerpt: "You don't grow in the gym — you grow while you sleep. Skimp on it and you sabotage everything else.",
    tag: "Recovery", date: "2026-02-22", readMins: 4,
    body: [
      { p: "Training breaks muscle down; recovery builds it back stronger. The single biggest recovery tool isn't a supplement or a massage gun — it's sleep, and most people get too little." },
      { h: "What poor sleep does to your physique" },
      { ul: ["Cuts muscle protein synthesis and recovery", "Raises hunger hormones — you eat more, especially junk", "Lowers training performance and willpower", "Increases fat retention when dieting"] },
      { h: "Aim for 7-9 hours" },
      { p: "Consistency matters as much as duration. Same sleep and wake times, a dark cool room, and no screens for the last 30 minutes do more than any pill. If you train hard, treat sleep as part of the program, not optional." },
      { p: "PRIME tracks your sleep alongside training and nutrition because the three rise and fall together — and a bad-sleep week shows up in everything else." },
    ],
  },
  {
    slug: "reading-food-labels-barcode",
    title: "Reading Food Labels & Logging by Barcode",
    excerpt: "Packaged foods hide a lot. Two minutes of label literacy saves your deficit.",
    tag: "Nutrition", date: "2026-02-15", readMins: 4,
    body: [
      { p: "Packaged and restaurant foods are where hidden calories live. Learning to read a label — and logging accurately — is a skill that pays off for life." },
      { h: "What to check first" },
      { ul: ["Serving size — the numbers are per serving, not per pack", "Calories per serving (and how many servings you'll really eat)", "Protein — your most important macro", "Added sugar and oils hiding in the ingredient list"] },
      { h: "Watch the serving-size trick" },
      { p: "A snack pack may list 90 calories per serving but contain 2.5 servings. Always multiply by what you actually eat. Drinks and condiments are notorious for this." },
      { p: "PRIME lets you scan a barcode to pull nutrition straight from the Open Food Facts database, or snap a photo of a meal for an AI estimate — so logging packaged and home food is fast and honest." },
    ],
  },
  {
    slug: "returning-to-gym-after-break",
    title: "Returning to the Gym After a Long Break",
    excerpt: "Muscle memory is real — but your first week back should still be humble. Here's the smart restart.",
    tag: "Getting Started", date: "2026-02-08", readMins: 4,
    body: [
      { p: "Took months or years off? Good news: thanks to muscle memory, you'll regain old strength and size far faster than it took to build the first time. Bad news: your ego remembers your old weights, but your tendons don't." },
      { h: "Start at about half" },
      { p: "For your first week back, use roughly 50% of what you used to lift and keep effort around 5-6 out of 10. It'll feel too easy — that's the point. You're reawakening movement patterns and prepping connective tissue, not testing maxes." },
      { h: "Expect (and respect) soreness" },
      { ul: ["DOMS will be brutal after the first sessions — ramp volume slowly", "Prioritise sleep, protein and water that first fortnight", "Add load weekly; you'll climb back fast"] },
      { p: "Tell PRIME you're returning after a break and it adds a one-week reintroduction phase before your main program — lighter, technique-focused, and built to avoid the classic week-one injury." },
    ],
  },
  {
    slug: "realistic-goal-timeframe",
    title: "Setting a Realistic Timeframe for Your Goal",
    excerpt: "Wanting to lose 15kg in a month is how plans die. Here's what's actually achievable — and safe.",
    tag: "Mindset", date: "2026-02-01", readMins: 4,
    body: [
      { p: "The fastest way to fail is to set a timeline your body can't safely meet. Aggressive targets force extreme deficits, muscle loss, and burnout — then the rebound." },
      { h: "Safe rates of change" },
      { ul: ["Fat loss: about 0.5-1% of body weight per week", "Muscle gain: far slower — 0.25-0.5kg per month for naturals", "A 10kg fat loss realistically takes about 3-5 months"] },
      { h: "Let the math set the calories" },
      { p: "Once you pick a goal weight and a sensible timeframe, the required weekly rate determines your calorie target — not the other way around. If the timeframe is too aggressive, the honest move is to extend it rather than crash-diet." },
      { p: "In PRIME you enter your goal weight and a target timeframe; it calculates the calories needed and, if your timeline is unsafe, automatically caps the rate and tells you the realistic finish date." },
    ],
  },
  {
    slug: "carbs-in-indian-diet",
    title: "The Role of Carbs in an Indian Diet",
    excerpt: "Rice and roti aren't the enemy. Quantity and context are what matter.",
    tag: "Indian Diet", date: "2026-01-25", readMins: 5,
    body: [
      { p: "Indian food is carb-rich by nature — rice, roti, dosa, poha. Low-carb influencers would have you fear them, but carbs aren't inherently fattening. Eating more calories than you burn is." },
      { h: "What carbs do for you" },
      { ul: ["Fuel hard training and daily energy", "Help you recover and build muscle", "Make food enjoyable and sustainable — adherence matters most"] },
      { h: "How to include them smartly" },
      { p: "Anchor meals with protein and vegetables, then add a controlled carb portion. Favour whole sources — millets, brown rice, oats, fruit, legumes — for more fibre and fullness. Time bigger carb portions around training if it suits you." },
      { h: "The real lever is total calories" },
      { p: "You can lose fat eating rice daily, as long as your total calories and protein are right. PRIME sets your carbs as whatever's left after protein and fat are covered — so you keep your roti and still hit your goal." },
    ],
  },
  {
    slug: "staying-consistent-streaks-habits",
    title: "Staying Consistent: Streaks, Habits, and the 1% Rule",
    excerpt: "Motivation fades. Systems don't. Here's how to keep going when you don't feel like it.",
    tag: "Mindset", date: "2026-01-18", readMins: 5,
    body: [
      { p: "Nobody feels motivated every day. The people who transform aren't more motivated — they've built systems that keep them moving on the days motivation is gone." },
      { h: "Shrink the bar on bad days" },
      { p: "Can't face the full workout? Do 10 minutes. Too busy to cook? Hit your protein with simple foods. A small action keeps the identity and the streak alive — and small actions compound. Getting 1% better most days beats a perfect week followed by quitting." },
      { h: "Use streaks and cues" },
      { ul: ["Track a daily streak — you won't want to break it", "Attach habits to existing routines (log dinner right after eating)", "Make the next action obvious and easy", "Forgive a missed day fast; never miss twice"] },
      { p: "PRIME turns this into a game: a daily completion score, streaks, achievement badges, and optional reminders so showing up becomes the default. Consistency, not intensity, is the real secret — and it's the one thing nobody can do for you." },
    ],
  },
];

export const TAGS = Array.from(new Set(POSTS.map((p) => p.tag)));
export function allSlugs() { return POSTS.map((p) => p.slug); }
export function getPost(slug) { return POSTS.find((p) => p.slug === slug) || null; }
export function sortedPosts() { return POSTS.slice().sort((a, b) => (a.date < b.date ? 1 : -1)); }
